akshat5302 patch 1
openSUSE/get-o-o pull request #74
Opened 2022-03-17 13:25 UTC by akshat5302

Updated the 15.2 and 15.1 states to 'EOL' in the releases.yml file

2022-03-17 13:25 UTC, akshat5302 commented
Updated releases.yml file

2022-03-18 02:23 UTC, hellcp requested changes
You should create a new entry for the EOL state instead of modifying the existing one

2022-03-18 05:24 UTC, akshat5302 reviewed
Added new states as EOL in versions 15.1 and 15.2

2022-03-18 12:26 UTC, hellcp commented
Probably worth looking up the actual dates of when both releases were deprecated on [the wiki](https://en.opensuse.org), otherwise there's a dash after releases line in 15.1

2022-03-19 01:44 UTC, akshat5302 reviewed
Checked and edited EOL dates according to wiki

2022-03-19 04:26 UTC, hellcp commented
releases line still has a dash, please correct it

2022-03-20 03:25 UTC, akshat5302 commented
> releases line still has a dash, please correct it

I couldn't able to find dash could you just elaborate on the issue

2022-03-20 03:26 UTC, hellcp commented on _data/releases.yml
> +  releases:-
```suggestion
  releases:
```

2022-03-20 03:33 UTC, akshat5302 reviewed
This change had been done by you I think it's not showing in my file

2022-03-20 03:34 UTC, hellcp approved these changes

2022-03-20 03:50 UTC, akshat5302 commented
Closing this PR now ??

2022-03-20 03:51 UTC, merged